import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Footer, Navbar } from "../../components"
import { Toaster } from "react-hot-toast"

import Providers from "../../components/Providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Headphones Story",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster />
          <div className="p-2.5 bg-[#F3F4F6]">
            <header>
              <Navbar />
            </header>
            <main className="max-w-357 w-full m-auto">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  )
}
